# Generated by Django 3.2.6 on 2021-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='ID_num',
            field=models.CharField(max_length=50),
        ),
    ]
