# Generated by Django 3.2.6 on 2021-09-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_costomer_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('room_catagory', models.CharField(max_length=40)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.costomer')),
            ],
        ),
    ]
