# Generated by Django 3.2.6 on 2021-09-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cust_id',
        ),
    ]
