# Generated by Django 3.2.6 on 2021-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_booking_cust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCategory', models.CharField(max_length=50)),
                ('CheckIN', models.DateField()),
                ('CheckOUT', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
