# Generated by Django 3.2.6 on 2021-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210910_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=60)),
                ('room_rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
