# Generated by Django 3.2.6 on 2021-10-08 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingRoom',
        ),
        migrations.RenameField(
            model_name='costomer',
            old_name='females',
            new_name='Adults',
        ),
        migrations.RemoveField(
            model_name='costomer',
            name='males',
        ),
        migrations.AddField(
            model_name='costomer',
            name='CheckIN',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 7, 58, 57, 949081, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='costomer',
            name='CheckOUT',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 7, 58, 57, 949194, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='costomer',
            name='RoomCategory',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
