# Generated by Django 3.2.6 on 2021-10-08 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20211008_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costomer',
            old_name='phoneNo',
            new_name='Phone',
        ),
        migrations.AlterField(
            model_name='costomer',
            name='CheckIN',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 8, 43, 26, 826845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='costomer',
            name='CheckOUT',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 8, 43, 26, 826872, tzinfo=utc)),
        ),
    ]
